export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const DEL_USER_SUCCESS = 'DEL_USER_SUCCESS'
export const RECEIVE_USERS = 'RECEIVE_USERS'

export const RECEIVE_INVENTORIES = 'RECEIVE_INVENTORIES'
export const ACTIVE_INVENTORY_ID = 'ACTIVE_INVENTORY_ID'
export const SAVE_INVENTORY_SUCCESS = 'SAVE_INVENTORY_SUCCESS'

export const RECEIVE_TODOS = 'RECEIVE_TODOS'
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS'
export const ACTIVE_TODO_ID = 'ACTIVE_TODO_ID'
